services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./src/backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend/dashboard
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/dashboard/src:/app/src
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend:/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

volumes:
  postgres_data: